KAU-SMART-PETS/Capstone_BE

Dockerfile, build.gradle
- cloase #4 
Docker file 생성해두었습니다.
- 
- 
=> infra: Docker 파일 생성

build.gradle
- close #9 
- 의존성 정리는 커밋 상세 내용에 삭제 이유 적어두었습니다 ~
- 
=> [CHORE] h2 의존성 추가 및 기존 의존성 정리

src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java, src/main/java/com/kau/capstone/domain/pet/dto/request/PetRegistRequest.java, src/main/java/com/kau/capstone/domain/pet/entity/Pet.java, src/main/java/com/kau/capstone/domain/pet/repository/PetRepository.java, src/main/java/com/kau/capstone/domain/pet/service/PetService.java, src/main/java/com/kau/capstone/domain/pet/util/PetMapper.java, src/main/java/com/kau/capstone/global/common/BaseEntity.java, src/main/java/com/kau/capstone/global/common/Gender.java, src/main/java/com/kau/capstone/global/common/PetType.java, src/main/java/com/kau/capstone/global/exception/ErrorCode.java, src/main/java/com/kau/capstone/global/exception/InvalidGenderException.java, src/main/java/com/kau/capstone/global/exception/NotExistPetTypeException.java
=> [FEAT] 반려동물 등록 api 생성

src/main/java/com/kau/capstone/domain/auth/controller/AuthController.java, src/main/java/com/kau/capstone/domain/auth/dto/LoginInfo.java, src/main/java/com/kau/capstone/domain/auth/exception/AuthException.java, src/main/java/com/kau/capstone/domain/auth/service/AuthService.java, src/main/java/com/kau/capstone/domain/auth/util/AuthArgumentResolver.java, src/main/java/com/kau/capstone/domain/auth/util/AuthHandlerInterceptor.java, src/main/java/com/kau/capstone/domain/auth/util/LoginUser.java, src/main/java/com/kau/capstone/global/common/WebConfig.java, src/main/java/com/kau/capstone/global/exception/ErrorCode.java
- close #11 
- 코멘트로 코드 설명해두었습니다!
- 사용자 인증이 필요한 경우에는 `@LoginUser LoginInfo loginInfo`로 사용하시면 됩니다
- 
=> [FEAT] 임시 로그인 기능 추가

.github/workflows/gradle.yml
=> fix: CI 실행시 PR에서 수정된 application.yml 코드가 적용되지 않는 버그 수정

src/main/java/com/kau/capstone/domain/auth/dto/NaverAccessTokenResponse.java, src/main/java/com/kau/capstone/domain/auth/dto/NaverUserInfoResponse.java, src/main/java/com/kau/capstone/domain/auth/util/SocialSite.java, src/main/java/com/kau/capstone/domain/auth/util/provider/NaverProvider.java, src/main/java/com/kau/capstone/domain/auth/util/provider/access/NaverAccessToken.java, src/main/java/com/kau/capstone/domain/auth/util/provider/logout/NaverLogout.java, src/main/java/com/kau/capstone/domain/auth/util/provider/redirect/NaverRedirect.java, src/main/java/com/kau/capstone/domain/auth/util/provider/secret/NaverSecretValue.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/test/resources/application.yml
- close #18 
- 
로컬 테스트 결과
- 네이버 로그아웃은 어드민이 강제 로그아웃이 불가능해서 카카오 로그아웃과 함께 다음 PR에서 업데이트할 예정입니다.
=> [FEAT]네이버 소셜 로그인 추가

src/main/java/com/kau/capstone/domain/member/controller/MemberController.java, src/main/java/com/kau/capstone/domain/member/dto/MemberInfoResponse.java, src/main/java/com/kau/capstone/domain/member/dto/ModifyMemberRequest.java, src/main/java/com/kau/capstone/domain/member/entity/Member.java, src/main/java/com/kau/capstone/domain/member/service/MemberService.java
- close #26 
- 내 기기 조회는 아직 디바이스 관련 코드가 없어서 진행 X
- 내 반려동물 조회는 `반려동물 정보 조회 API 생성` PR이 Merge 된 이후 진행 예정
- 
=> feat: 유저 정보 조회, 유저 정보 수정 기능 추가

src/main/java/com/kau/capstone/domain/walk/entity/Walk.java
- close #29
- 
인터넷에 많이 나와있는 기준으로 정했습니다.
- 1M당 1.2보로 측정 (100M 120보)
- 한 걸음당 0.04kcal로 측정
=> feat: 산책 엔티티 추가

build.gradle, src/main/java/com/kau/capstone/global/config/SwaggerConfig.java
- close #38 
- 간단하게 스웨거 설정만 해두었습니다.
- 
=> feat: API 문서 자동화 추가

src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java, src/main/java/com/kau/capstone/domain/pet/dto/request/UpdatePetInfoRequest.java, src/main/java/com/kau/capstone/domain/pet/dto/response/PetInfoResponse.java, src/main/java/com/kau/capstone/domain/pet/entity/Gender.java, src/main/java/com/kau/capstone/domain/pet/entity/Pet.java, src/main/java/com/kau/capstone/domain/pet/entity/PetType.java, src/main/java/com/kau/capstone/domain/pet/service/PetService.java, src/main/java/com/kau/capstone/domain/pet/util/PetMapper.java
- close #35 
- 반려동물 정보 수정 api 생성하였습니다.
- 반려동물 이미지 수정 기능은 추후 s3에 이미지 업로드 로직 생성 시 추가하겠습니다.
- 
=> feat: 반려동물 정보 수정 기능

src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java, src/main/java/com/kau/capstone/domain/pet/entity/Pet.java, src/main/java/com/kau/capstone/domain/pet/service/PetService.java
- close #36 
- 반려동물 정보 삭제 기능입니다.
- 삭제는 soft delete 사용하였습니다.
- 
=> feat: 반려동물 정보 삭제 기능

src/test/java/com/kau/capstone/domain/member/entity/MemberTest.java
- close #39 
- 이름만, 이메일만 테스트는 private 메서드 로직도 테스트 할 수 있게 만들었습니다.
- 
=> test: 유저 단위 테스트 추가

src/main/java/com/kau/capstone/domain/member/entity/Member.java, src/main/java/com/kau/capstone/domain/member/entity/pet/OwnedPet.java, src/main/java/com/kau/capstone/domain/member/repository/OwnedPetRepository.java, src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java, src/main/java/com/kau/capstone/domain/pet/service/PetService.java
- close #47 
```mermaid
erDiagram
User {
int id
}
Pet {
int id
}
OwnedPet {
int user_id
int pet_id
}
User ||--o{ OwnedPet : ""
Pet ||--|| OwnedPet : ""
```
- 유저가 등록한 반려동물 목록을 제공하기 위해 `OwnedPet`을 추가 했습니다. 더 좋은 네이밍 있으면 추천점요
- 반려동물 목록 기반으로 조회 / 수정 / 삭제를 사용하는 주체가 `Member`라서 `Member` 패키지 안에 두었습니다.
- `OwnedPetService`를 만들까 생각해봤는데 서비스끼리 의존성을 가지면 나중에 고생할 수 있을 것 같아서 Repository만 의존성 가지도록 했습니다.
- 
* P3 : 이런 방법도 있을 것 같아요~ 등의 …
=> feat: 유저가 반려동물 등록시 유저와 반려동물 정보를 연결

build.gradle, src/main/java/com/kau/capstone/domain/auth/util/SocialSite.java, src/test/java/com/kau/capstone/common/TestProvider.java, src/test/java/com/kau/capstone/common/access/TestAccessToken.java, src/test/java/com/kau/capstone/common/logout/TestLogout.java, src/test/java/com/kau/capstone/common/redirect/TestRedirect.java, src/test/java/com/kau/capstone/common/refresh/TestRefreshToken.java, src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java, src/test/java/com/kau/capstone/domain/member/service/TestMemberService.java, src/test/resources/application.yml
- close #41 
- TestProvider에 카카오 클래스를 주입해둬서 수정하기
- 
=> test: 유저 E2E 테스트 추가

src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java, src/main/resources/application-local.yml, src/main/resources/application.yml
=> bug: pet pathVariable 수정

.github/workflows/deploy.yml
=> fix: 배포 코드 수정

src/test/java/com/kau/capstone/domain/member/service/TestMemberService.java
(CI가 MemberService 코드가 수정되기 이전에 돌아가서 문제가 없었던 것으로 보임)
- close #61 
- CI가 MemberService 코드가 수정되기 이전에 돌아가서 문제가 없었던 것으로 보임
- 
=> fix: 프로덕션 로직 업데이트로 인한 TestMemberService 로직 수정

.github/workflows/deploy.yml
- close #
- 원인을 파악했으므로 코드 복구
- 
=> fix: deploy 코드 복구

src/main/java/com/kau/capstone/domain/member/controller/MemberController.java, src/main/java/com/kau/capstone/domain/member/dto/OwnedPetResponse.java, src/main/java/com/kau/capstone/domain/member/dto/OwnedPetsResponse.java, src/main/java/com/kau/capstone/domain/member/repository/OwnedPetRepository.java, src/main/java/com/kau/capstone/domain/member/service/MemberService.java
=> feat: 사용자가 등록한 반려동물 목록 조회

src/main/java/com/kau/capstone/domain/vet/controller/VetController.java, src/main/java/com/kau/capstone/domain/vet/dto/MemberLocationRequest.java, src/main/java/com/kau/capstone/domain/vet/dto/VetDetailResponse.java, src/main/java/com/kau/capstone/domain/vet/entity/Vet.java, src/main/java/com/kau/capstone/domain/vet/service/VetService.java
- close #66 
여기에 있는 900m 기능 제공
사용자가 동물병원 위치를 계산하느냐, 동물병원이 사용자 위치를 계산하느냐의 차이는 동물병원에 추가하기로 결정함
- 이유: 사용자 로직에 다른 내용들도 추가될 예정이라 상대적으로 코드가 적은 동물병원이 관리하는게 나아보임
- 거리 계산 로직은 `Vet.java`에 만들어둠
=> feat: 동물 병원과 사용자 사이의 거리를 제공하는 값 추가

src/main/java/com/kau/capstone/domain/vet/controller/VetController.java, src/main/java/com/kau/capstone/domain/vet/dto/VetResponse.java
=> refactor: 동물병원 목록 API 응답 데이터 수정

src/main/java/com/kau/capstone/domain/member/controller/MemberController.java, src/main/java/com/kau/capstone/domain/member/dto/MemberInfoResponse.java, src/main/java/com/kau/capstone/domain/member/dto/ModifyMemberRequest.java, src/main/java/com/kau/capstone/domain/member/entity/Member.java, src/main/java/com/kau/capstone/domain/member/service/MemberService.java, src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java, src/test/java/com/kau/capstone/domain/member/entity/MemberTest.java
- close #78 
- SMS 수신 추가
- 이메일 수신 추가
- 휴대폰 번호 추가
- 이름 (name)
- 이메일 (email)
- 휴대폰 번호 (phoneNumber)
- SMS 수신 (smsOptIn)
- 이메일 수신 (emailOptIn)
- [아직 반영 X] 포인트 (point), 소셜 로그인 플랫폼 (socialType)
- 이메일
- 휴대폰 번호
- SMS 수신
- 이메일 수신
- 
=> refactor: 사용자 기능 API 업데이트

src/main/java/com/kau/capstone/global/common/WebConfig.java
=> feat: 사용자, 반려동물 경로에 로그인 인터셉터 추가

src/main/java/com/kau/capstone/domain/auth/controller/AuthController.java, src/main/java/com/kau/capstone/domain/member/controller/MemberController.java, src/main/java/com/kau/capstone/domain/vet/controller/VetApi.java, src/main/java/com/kau/capstone/domain/vet/controller/VetController.java
=> [feat] 동물병원 Swagger 문서 추가

src/main/java/com/kau/capstone/domain/member/controller/MemberController.java, src/main/java/com/kau/capstone/domain/member/dto/PayPointRequest.java, src/main/java/com/kau/capstone/domain/member/entity/Member.java, src/main/java/com/kau/capstone/domain/member/exception/PointNotEnoughException.java, src/main/java/com/kau/capstone/domain/member/service/MemberService.java, src/main/java/com/kau/capstone/global/exception/ErrorCode.java, src/test/java/com/kau/capstone/domain/member/entity/MemberTest.java
=> feat: 포인트 결제 기능 추가

src/main/java/com/kau/capstone/domain/food/entity/Food.java
=> feat: 사료 엔티티 추가

src/main/java/com/kau/capstone/domain/food/controller/FoodController.java, src/main/java/com/kau/capstone/domain/food/dto/FoodResponse.java, src/main/java/com/kau/capstone/domain/food/dto/FoodsResponse.java, src/main/java/com/kau/capstone/domain/food/repository/FoodRepository.java, src/main/java/com/kau/capstone/domain/food/service/FoodService.java
=> feat: 사료 목록 조회 API 추가

src/main/java/com/kau/capstone/domain/member/controller/MemberController.java, src/main/java/com/kau/capstone/domain/member/dto/EarnPointRequest.java, src/main/java/com/kau/capstone/domain/member/entity/Member.java, src/main/java/com/kau/capstone/domain/member/service/MemberService.java, src/test/java/com/kau/capstone/domain/member/entity/MemberTest.java
=> feat: 포인트 획득 API 추가

src/main/java/com/kau/capstone/global/common/WebConfig.java
- close #88 
- setMaxAge 기본값이 1800초 (= 30분)이라 따로 설정해두지는 않았음 
- 
=> feat: cors 설정 추가

src/main/java/com/kau/capstone/global/exception/ErrorCode.java, src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java
=> test: 포인트 결제, 포인트 획득 E2E 테스트 추가

src/main/java/com/kau/capstone/domain/auth/service/AuthService.java, src/main/java/com/kau/capstone/domain/food/service/FoodService.java, src/main/java/com/kau/capstone/domain/member/service/MemberService.java, src/main/java/com/kau/capstone/domain/vet/service/VetService.java
- close #95
- H2에서는 readOnly 옵션이 무시되서 테스트는 정상적으로 나오지만, 실서비스는 MySQL을 사용하므로 옵션 수정
- 나중에 급하게 수정하다가 에러가 나올지 모르니 readOnly 옵션 자체를 제거합니다
- 
=> fix: 트랜잭션 옵션 수정

src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java, src/test/java/com/kau/capstone/global/common/ControllerTest.java
=> test: 사용자가 등록한 반려동물 목록 조회 API 테스트 추가

src/main/java/com/kau/capstone/domain/member/dto/MemberInfoResponse.java, src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java
=> refactor: 유저 정보 조회 API를 수정된 요구사항에 맞게 변경

src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java
=> test: 포인트 획득 E2E 테스트 추가

src/test/java/com/kau/capstone/domain/vet/controller/VetControllerTest.java, src/test/java/com/kau/capstone/global/common/ControllerTest.java
=> test: 동물병원 관련 기능 E2E 테스트 추가

src/test/java/com/kau/capstone/domain/food/controller/FoodControllerTest.java, src/test/java/com/kau/capstone/global/common/ControllerTest.java
=> test: 사료 목록 조회 E2E 테스트 추가

src/main/java/com/kau/capstone/domain/bluetooth/controller/BluetoothController.java, src/main/java/com/kau/capstone/domain/bluetooth/dto/OneOwnedBluetoothResponse.java, src/main/java/com/kau/capstone/domain/bluetooth/dto/OwnedBluetoothResponse.java, src/main/java/com/kau/capstone/domain/bluetooth/entity/Bluetooth.java, src/main/java/com/kau/capstone/domain/bluetooth/entity/member/OwnedBluetooth.java, src/main/java/com/kau/capstone/domain/bluetooth/repository/BluetoothRepository.java, src/main/java/com/kau/capstone/domain/bluetooth/repository/OwnedBluetoothRepository.java, src/main/java/com/kau/capstone/domain/bluetooth/service/BluetoothService.java, src/test/java/com/kau/capstone/domain/bluetooth/controller/BluetoothControllerTest.java, src/test/java/com/kau/capstone/global/common/ControllerTest.java
=> feat: 사용자가 등록한 블루투스 기기 목록 조회 기능 추가

src/main/java/com/kau/capstone/domain/bluetooth/controller/BluetoothController.java, src/main/java/com/kau/capstone/domain/bluetooth/dto/BluetoothRegistryRequest.java, src/main/java/com/kau/capstone/domain/bluetooth/service/BluetoothService.java, src/test/java/com/kau/capstone/domain/bluetooth/controller/BluetoothControllerTest.java
=> feat: 사용자가 블루투스 기기를 등록할 수 있는 기능 추가

src/main/java/com/kau/capstone/domain/point/controller/PointController.java, src/main/java/com/kau/capstone/domain/point/dto/HistoryResponse.java, src/main/java/com/kau/capstone/domain/point/dto/OneHistoryResponse.java, src/main/java/com/kau/capstone/domain/point/entity/history/History.java, src/main/java/com/kau/capstone/domain/point/repository/HistoryRepository.java, src/main/java/com/kau/capstone/domain/point/service/PointService.java, src/test/java/com/kau/capstone/domain/point/controller/PointControllerTest.java
=> feat: 포인트 적립/결제 내역 기능 추가

src/main/java/com/kau/capstone/domain/food/controller/FoodController.java, src/main/java/com/kau/capstone/domain/food/exception/FoodNotFoundException.java, src/main/java/com/kau/capstone/domain/point/dto/DeliveryFeeRequest.java, src/main/java/com/kau/capstone/domain/point/service/PointService.java, src/main/java/com/kau/capstone/global/exception/ErrorCode.java, src/test/java/com/kau/capstone/domain/food/controller/FoodControllerTest.java, src/test/java/com/kau/capstone/domain/point/controller/PointControllerTest.java
=> feat: 사료 결제 기능 추가

src/main/java/com/kau/capstone/domain/vet/controller/VetApi.java, src/main/java/com/kau/capstone/domain/vet/controller/VetController.java, src/main/java/com/kau/capstone/domain/vet/entity/Vet.java, src/main/java/com/kau/capstone/domain/vet/repository/VetRepository.java, src/main/java/com/kau/capstone/domain/vet/service/VetService.java, src/test/java/com/kau/capstone/domain/vet/controller/VetControllerTest.java, src/test/resources/application.yml
=> refactor: 동물병원 목록 조회시 사용자와 가까운 동물병원 20개 제공으로 API 변경

src/main/java/com/kau/capstone/domain/vet/controller/VetApi.java
=> refactor: 동물병원 스웨거 문서 수정

src/main/java/com/kau/capstone/domain/bluetooth/service/BluetoothService.java, src/main/java/com/kau/capstone/domain/member/service/MemberService.java, src/main/java/com/kau/capstone/domain/pet/service/PetService.java, src/main/java/com/kau/capstone/domain/point/service/PointService.java, src/main/java/com/kau/capstone/domain/reward/controller/RewardController.java, src/main/java/com/kau/capstone/domain/reward/dto/RewardResponse.java, src/main/java/com/kau/capstone/domain/reward/dto/RewardsResponse.java, src/main/java/com/kau/capstone/domain/reward/entity/Reward.java, src/main/java/com/kau/capstone/domain/reward/entity/RewardDetail.java, src/main/java/com/kau/capstone/domain/reward/repository/RewardRepository.java, src/main/java/com/kau/capstone/domain/reward/service/RewardService.java, src/test/java/com/kau/capstone/domain/member/service/TestMemberService.java, src/test/java/com/kau/capstone/domain/reward/controller/RewardControllerTest.java
- close #76 
- 리워드 관련 테스트를 할 경우 `getCookie(...)`로 등록해야함
- 
=> feat: 리워드 기능 추가 및 리워드 목록 조회

src/main/java/com/kau/capstone/domain/point/service/PointService.java, src/main/java/com/kau/capstone/domain/reward/controller/RewardController.java, src/main/java/com/kau/capstone/domain/reward/dto/RewardResponse.java, src/main/java/com/kau/capstone/domain/reward/entity/Reward.java, src/main/java/com/kau/capstone/domain/reward/exception/RewardNotFoundException.java, src/main/java/com/kau/capstone/global/exception/ErrorCode.java, src/test/java/com/kau/capstone/domain/reward/controller/RewardControllerTest.java
=> feat: 리워드 달성시 포인트 적립 기능 추가

src/main/java/com/kau/capstone/domain/alarm/controller/AlarmController.java, src/main/java/com/kau/capstone/domain/alarm/dto/AlarmResponse.java, src/main/java/com/kau/capstone/domain/alarm/dto/OneAlarmResponse.java, src/main/java/com/kau/capstone/domain/alarm/entity/Alarm.java, src/main/java/com/kau/capstone/domain/alarm/entity/AlarmDetail.java, src/main/java/com/kau/capstone/domain/alarm/repository/AlarmRepository.java, src/main/java/com/kau/capstone/domain/alarm/service/AlarmService.java, src/main/java/com/kau/capstone/domain/member/service/MemberService.java, src/main/java/com/kau/capstone/domain/pet/service/PetService.java, src/main/java/com/kau/capstone/domain/point/service/PointService.java, src/test/java/com/kau/capstone/domain/alarm/controller/AlarmControllerTest.java, src/test/java/com/kau/capstone/domain/member/service/TestMemberService.java
=> feat: 알람 기능 추가

src/main/java/com/kau/capstone/domain/vet/controller/VetApi.java, src/main/java/com/kau/capstone/domain/vet/controller/VetController.java, src/test/java/com/kau/capstone/domain/vet/controller/VetControllerTest.java
=> feat: 동물병원 목록 조회 HTTP 메서드 변경

src/main/java/com/kau/capstone/domain/vet/controller/VetApi.java, src/main/java/com/kau/capstone/domain/vet/controller/VetController.java, src/test/java/com/kau/capstone/domain/vet/controller/VetControllerTest.java
=> fix: 동물병원 세부 목록 조회 HTTP 메서드 변경

src/main/java/com/kau/capstone/domain/vaccination/controller/VaccinationController.java, src/main/java/com/kau/capstone/domain/vaccination/dto/CreateVaccinationRequest.java, src/main/java/com/kau/capstone/domain/vaccination/dto/OneVaccinationResponse.java, src/main/java/com/kau/capstone/domain/vaccination/dto/PetVaccinationResponse.java, src/main/java/com/kau/capstone/domain/vaccination/dto/PutVaccinationRequest.java, src/main/java/com/kau/capstone/domain/vaccination/dto/VaccinationsResponse.java, src/main/java/com/kau/capstone/domain/vaccination/entity/Vaccination.java, src/main/java/com/kau/capstone/domain/vaccination/exception/VaccinationNotFoundException.java, src/main/java/com/kau/capstone/domain/vaccination/repository/VaccinationRepository.java, src/main/java/com/kau/capstone/domain/vaccination/service/VaccinationService.java, src/main/java/com/kau/capstone/global/exception/ErrorCode.java, src/test/java/com/kau/capstone/domain/vaccination/controller/VaccinationControllerTest.java, src/test/java/com/kau/capstone/global/common/ControllerTest.java
=> feat: 보건정보 기능 CRUD 추가

src/main/java/com/kau/capstone/domain/pet/util/PetHandlerInterceptor.java, src/main/java/com/kau/capstone/global/common/WebConfig.java
=> feat: 로그인이 필요한 API 인터셉터 추가

src/main/java/com/kau/capstone/domain/alarm/controller/AlarmApi.java, src/main/java/com/kau/capstone/domain/alarm/controller/AlarmController.java, src/main/java/com/kau/capstone/domain/auth/controller/AuthApi.java, src/main/java/com/kau/capstone/domain/auth/controller/AuthController.java, src/main/java/com/kau/capstone/domain/bluetooth/controller/BluetoothApi.java, src/main/java/com/kau/capstone/domain/bluetooth/controller/BluetoothController.java, src/main/java/com/kau/capstone/domain/food/controller/FoodApi.java, src/main/java/com/kau/capstone/domain/food/controller/FoodController.java, src/main/java/com/kau/capstone/domain/member/controller/MemberApi.java, src/main/java/com/kau/capstone/domain/member/controller/MemberController.java, src/main/java/com/kau/capstone/domain/point/controller/PointApi.java, src/main/java/com/kau/capstone/domain/point/controller/PointController.java, src/main/java/com/kau/capstone/domain/reward/controller/RewardApi.java, src/main/java/com/kau/capstone/domain/reward/controller/RewardController.java, src/main/java/com/kau/capstone/domain/vaccination/controller/VaccinationApi.java, src/main/java/com/kau/capstone/domain/vaccination/controller/VaccinationController.java, src/main/java/com/kau/capstone/domain/vet/controller/VetApi.java
=> docs: Swagger 문서 업데이트

src/main/java/com/kau/capstone/domain/member/controller/MemberApi.java
=> fix: swagger 이름 변경

src/main/java/com/kau/capstone/domain/auth/controller/AuthController.java
- close #140 
- 프론트 없이 테스트가 불가능해서 GET 추가
- 
=> feat: 소셜 로그인 HTTP 메서드 추가 지원

src/main/java/com/kau/capstone/domain/auth/controller/AuthApi.java
=> docs: 소셜 로그인 API Swagger 업데이트

src/main/java/com/kau/capstone/domain/point/repository/HistoryRepository.java, src/test/java/com/kau/capstone/domain/point/controller/PointControllerTest.java
=> fix: 포인트 내역 조회를 최신순으로 볼 수 있도록 수정

src/main/java/com/kau/capstone/domain/auth/util/SocialSite.java
=> fix: 소셜 로그인을 로그아웃할시 로그인 사이트를 찾지 못하는 버그 수정

src/main/java/com/kau/capstone/domain/auth/util/SocialSite.java, src/main/java/com/kau/capstone/global/exception/ErrorCode.java
=> fix: 소셜 로그인 탐색과 소셜 로그인 링크를 받는 과정에서 발생하는 에러 메시지 분리

src/main/java/com/kau/capstone/global/exception/GlobalExceptionHandler.java
=> feat: 예상하지 못한 에러 발생시 문제 원인을 파악할 수 있도록 메시지 추가

src/main/java/com/kau/capstone/domain/pet/dto/request/PetRegistRequest.java
- close #149 
- float로 인해 에러 발생
- 
=> fix: 반려동물 등록시 몸무게를 Float > Double로 변경

src/main/java/com/kau/capstone/domain/vaccination/repository/VaccinationRepository.java
=> fix: 보건정보 조회를 예방접종 최신순으로 변경

src/main/java/com/kau/capstone/domain/vet/controller/VetController.java, src/main/java/com/kau/capstone/domain/vet/dto/VetDetailResponse.java, src/main/java/com/kau/capstone/domain/vet/service/VetService.java
=> refactor: 동물병원 세부 조회시 위도, 경도 데이터를 반환하도록 수정

src/main/java/com/kau/capstone/initial/FoodInitializer.java, src/main/java/com/kau/capstone/initial/VetInitializer.java
- close #156 
- ddl 옵션 변경시 해당 코드는 삭제 되어야 함
- 
=> feat: 모바일 결과물 확인을 위한 더미데이터 추가

src/main/java/com/kau/capstone/domain/ai/AIImage.java, src/main/java/com/kau/capstone/domain/ai/client/AIModelClient.java, src/main/java/com/kau/capstone/domain/ai/controller/AIController.java, src/main/java/com/kau/capstone/domain/ai/infra/S3StorageService.java, src/main/java/com/kau/capstone/domain/ai/service/AIService.java
=> feat: AI 모델 접근 서버 구현

src/main/java/com/kau/capstone/domain/pet/dto/request/PetRegistRequest.java
=> fix: validation 제거

src/main/java/com/kau/capstone/domain/vaccination/dto/OneVaccinationResponse.java
=> refactor: 백신 id 추가

src/main/java/com/kau/capstone/domain/member/entity/Member.java, src/main/java/com/kau/capstone/domain/member/service/MemberService.java
- close #162 
- 카카오 로그인 문서에서는 액세스 토큰으로 로그아웃시 액세스 토큰만 만료된다는데, 리프레시 토큰도 만료되어 KOE322 에러가 발생함
- 
=> bug: 기존 유저는 카카오 로그인시 리프레시토큰 정보를 변경할 수 있도록 수정

src/main/java/com/kau/capstone/domain/auth/controller/AuthApi.java, src/main/java/com/kau/capstone/domain/auth/controller/AuthController.java
=> refactor: 소셜 로그인/로그아웃 리다이렉트 제거

src/main/java/com/kau/capstone/domain/member/service/MemberService.java
=> fix: 삭제된 pet 조회 안되게 처리

src/main/java/com/kau/capstone/domain/pet/service/PetService.java
=> fix: pet 이미지 유무에 따른 로직 처리

src/main/java/com/kau/capstone/domain/member/service/MemberService.java
=> bug: 반려동물 목록 조회시 삭제된 반려동물 제외

src/main/resources/application-prod.yml
=> refactor: 세션 유지 시간을 늘리도록 변경

src/main/java/com/kau/capstone/domain/pet/dto/request/PetRegistRequest.java
=> fix: pet name 등록 시 대문자 영문도 허용

src/main/java/com/kau/capstone/domain/member/dto/MemberInfoResponse.java, src/main/java/com/kau/capstone/domain/member/repository/OwnedPetRepository.java, src/main/java/com/kau/capstone/domain/pet/entity/Pet.java, src/main/java/com/kau/capstone/domain/pet/repository/PetRepository.java, src/main/java/com/kau/capstone/domain/walk/controller/WalkController.java, src/main/java/com/kau/capstone/domain/walk/dto/request/WalkRequest.java, src/main/java/com/kau/capstone/domain/walk/dto/response/WalkDailySummaryResponse.java, src/main/java/com/kau/capstone/domain/walk/dto/response/WalkMonthlyResponse.java, src/main/java/com/kau/capstone/domain/walk/dto/response/WalkRecentDataListResponse.java, src/main/java/com/kau/capstone/domain/walk/dto/response/WalkRecentDataResponse.java, src/main/java/com/kau/capstone/domain/walk/dto/response/WalkResponse.java, src/main/java/com/kau/capstone/domain/walk/dto/response/WalkWeeklySummaryResponse.java, src/main/java/com/kau/capstone/domain/walk/entity/Walk.java, src/main/java/com/kau/capstone/domain/walk/repository/WalkRepository.java, src/main/java/com/kau/capstone/domain/walk/service/WalkService.java
- close #184 
- #183 
- #177 
- #170 
- #169 
일단 기능 구현을 우선적으로 개발해서 코드 자체가 DDD 설계에 부합하지 않음
해당 부분은 추후에 리팩토링 진행 할 예정 
- 
- 
=> Feat/산책 기능 추가 

src/main/resources/application-local.yml, src/main/resources/application-prod.yml
멀티파트 이미지 크기 조정 
- close #189 
- 
- 
=> fix : 멀티파트 이미지 크기 수정

src/main/java/com/kau/capstone/domain/ai/client/AIModelClient.java, src/main/java/com/kau/capstone/domain/ai/controller/AIController.java, src/main/java/com/kau/capstone/domain/ai/service/AIService.java
=> feat: regist pet nose

src/main/resources/application-local.yml, src/main/resources/application-prod.yml
=> fix: 파일 전송 용량 수정

src/main/java/com/kau/capstone/domain/member/repository/OwnedPetRepository.java, src/main/java/com/kau/capstone/domain/walk/controller/WalkController.java, src/main/java/com/kau/capstone/domain/walk/service/WalkService.java
=> refactor : WalkController 세션값으로 수정

src/main/java/com/kau/capstone/domain/walk/controller/WalkController.java, src/main/java/com/kau/capstone/domain/walk/repository/WalkRepository.java, src/main/java/com/kau/capstone/domain/walk/service/WalkService.java
=> refactor : 최근 산책 쿼리 수정

src/main/java/com/kau/capstone/domain/ai/client/AIModelClient.java, src/main/java/com/kau/capstone/domain/ai/controller/AIController.java, src/main/java/com/kau/capstone/domain/ai/service/AIService.java
=> feat: test nose

src/main/java/com/kau/capstone/domain/ai/controller/AIController.java
=> fix: 메소드 변경
